version: '3.8'

services:
  whatsapp-admin:
    build:
      context: .
      network: host
    container_name: green-api
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
